import { useMemo, useRef, useState } from "react";
import { Html, Text } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import OrbitalDiagram from "./OrbitalDiagram";
import Nucleus from "./Nucleus";
import ElectronShell from "./ElectronShell";
import { getElectronConfiguration, getShellConfiguration } from "../../data/electronConfiguration";
import "./atomPhysics.css";

function AtomicField({ intensity }) { const ref = useRef(); useFrame(({ clock }) => { if (!ref.current) return; const t = clock.elapsedTime; ref.current.rotation.y = t * 0.08; const pulse = 1 + Math.sin(t * 1.8) * 0.025 * intensity; ref.current.scale.setScalar(pulse); ref.current.material.opacity = 0.035 + Math.sin(t * 1.8) * 0.012 * intensity; }); return <mesh ref={ref}><sphereGeometry args={[1.18, 48, 48]} /><meshBasicMaterial color="#38bdf8" transparent opacity={0.035} depthWrite={false} wireframe /></mesh>; }
function EnergyWave({ radius, speed, color = "#38bdf8" }) { const ref = useRef(); useFrame(({ clock }) => { if (!ref.current) return; const phase = (clock.elapsedTime * speed) % 1; const scale = radius * (0.82 + phase * 0.28); ref.current.scale.set(scale, scale, scale); ref.current.material.opacity = (1 - phase) * 0.16; }); return <mesh ref={ref}><sphereGeometry args={[1, 32, 32]} /><meshBasicMaterial color={color} transparent opacity={0.1} wireframe depthWrite={false} /></mesh>; }

export default function Atom({ element, onInspect }) {
  const [energyMode, setEnergyMode] = useState("stable");
  const configuration = useMemo(() => getElectronConfiguration(element.number), [element.number]);
  const shells = useMemo(() => getShellConfiguration(element.number), [element.number]);
  const neutrons = Math.max(0, Math.round(Number(element.mass)) - element.number);
  const energyMultiplier = energyMode === "excited" ? 1.9 : energyMode === "ionized" ? 2.6 : 1;
  const legendStyle = { width: "min(420px, 72vw)", padding: "10px 13px", border: "1px solid rgba(148,163,184,.16)", borderRadius: "12px", background: "rgba(2,6,23,.86)", backdropFilter: "blur(14px)", boxShadow: "0 12px 35px rgba(0,0,0,.35)", color: "#cbd5e1", fontFamily: "Inter, system-ui, sans-serif", pointerEvents: "auto" };
  return <group>
    <AtomicField intensity={energyMultiplier} /><EnergyWave radius={1.45} speed={0.45 * energyMultiplier} /><EnergyWave radius={2.5} speed={0.32 * energyMultiplier} color="#a78bfa" />
    <Nucleus protons={element.number} neutrons={neutrons} onInspect={onInspect} />
    {shells.map((shell, index) => <ElectronShell key={shell.shell} shell={1.5 + index * 0.75} orbital={configuration.orbitals?.find((orbital) => Number(orbital.orbital[0]) === shell.shell)?.orbital || `Shell ${shell.shell}`} count={shell.electrons} speed={(1.4 / (index + 1)) * energyMultiplier} inclination={index % 2 === 0 ? 0 : Math.PI * 0.35} onInspect={onInspect} energyMode={energyMode} />)}
    <Html position={[0, 3.45, 0]} center distanceFactor={8} zIndexRange={[10, 20]}><div style={legendStyle} onPointerDown={(event) => event.stopPropagation()}><div style={{ fontSize: "7px", fontWeight: 800, letterSpacing: ".18em", color: "#64748b", marginBottom: "8px" }}>LIVE ATOMIC MODEL · PARTICLE KEY</div><div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "8px" }}><div style={{ display: "flex", alignItems: "center", gap: "6px" }}><span style={{ width: 9, height: 9, borderRadius: "50%", background: "#ef4444", boxShadow: "0 0 10px #ef4444" }} /><span><b style={{ display: "block", fontSize: "7px", color: "#fca5a5" }}>PROTON</b><small style={{ display: "block", fontSize: "5px", color: "#64748b" }}>+1 · NUCLEUS</small></span></div><div style={{ display: "flex", alignItems: "center", gap: "6px" }}><span style={{ width: 9, height: 9, borderRadius: "50%", background: "#64748b", boxShadow: "0 0 8px rgba(100,116,139,.7)" }} /><span><b style={{ display: "block", fontSize: "7px", color: "#cbd5e1" }}>NEUTRON</b><small style={{ display: "block", fontSize: "5px", color: "#64748b" }}>0 · NUCLEUS</small></span></div><div style={{ display: "flex", alignItems: "center", gap: "6px" }}><span style={{ width: 9, height: 9, borderRadius: "50%", background: "#38bdf8", boxShadow: "0 0 12px #38bdf8" }} /><span><b style={{ display: "block", fontSize: "7px", color: "#7dd3fc" }}>ELECTRON</b><small style={{ display: "block", fontSize: "5px", color: "#64748b" }}>−1 · ORBITAL</small></span></div></div></div></Html>
    <Html position={[0, -3.8, 0]} center distanceFactor={8} zIndexRange={[20, 30]}><div className="atom-physics-controls" onPointerDown={(event) => event.stopPropagation()}><div><span>ENERGY STATE</span><b>{energyMode.toUpperCase()}</b></div><div className="atom-physics-buttons"><button className={energyMode === "stable" ? "active" : ""} onClick={() => setEnergyMode("stable")}>STABLE</button><button className={energyMode === "excited" ? "active" : ""} onClick={() => setEnergyMode("excited")}>EXCITED</button><button className={energyMode === "ionized" ? "active" : ""} onClick={() => setEnergyMode("ionized")}>IONIZED</button></div><small>{energyMode === "stable" ? "Ground-state motion" : energyMode === "excited" ? "Faster visualized orbital motion" : "High-energy ionization mode"}</small></div></Html>
    <group position={[0, -3.2, 0]}><Text fontSize={0.45} color="white" anchorX="center" anchorY="middle">{element.symbol}</Text><Text position={[0, -0.45, 0]} fontSize={0.18} color="#94a3b8" anchorX="center" anchorY="middle">{element.name}</Text></group>
  </group>;
}