import { useMemo, useState } from "react";
import { Canvas } from "@react-three/fiber";
import { OrbitControls, Text } from "@react-three/drei";
import "./CombinationLab.css";

const ELEMENTS = [
  { symbol: "H", name: "Hydrogen", color: "#e2e8f0" }, { symbol: "O", name: "Oxygen", color: "#fb7185" },
  { symbol: "C", name: "Carbon", color: "#64748b" }, { symbol: "N", name: "Nitrogen", color: "#60a5fa" },
  { symbol: "Na", name: "Sodium", color: "#fbbf24" }, { symbol: "Cl", name: "Chlorine", color: "#a3e635" },
];
const PRESETS = {
  H2O:{formula:"H₂O",name:"Water",atoms:["H","H","O"],bond:"Polar covalent",geometry:"Bent",angle:"104.5°",mass:"18.015 g/mol",note:"Hydrogen atoms share electrons with oxygen. The bent geometry gives water a strong molecular dipole."},
  CO2:{formula:"CO₂",name:"Carbon dioxide",atoms:["O","C","O"],bond:"Polar covalent",geometry:"Linear",angle:"180°",mass:"44.01 g/mol",note:"Each C=O bond is polar, but the linear geometry cancels the bond dipoles overall."},
  CH4:{formula:"CH₄",name:"Methane",atoms:["C","H","H","H","H"],bond:"Covalent",geometry:"Tetrahedral",angle:"109.5°",mass:"16.043 g/mol",note:"Carbon forms four equivalent C–H bonds arranged tetrahedrally around the central atom."},
  NH3:{formula:"NH₃",name:"Ammonia",atoms:["N","H","H","H"],bond:"Polar covalent",geometry:"Trigonal pyramidal",angle:"107°",mass:"17.031 g/mol",note:"A lone pair on nitrogen pushes the three N–H bonds into a pyramidal arrangement."},
  O2:{formula:"O₂",name:"Oxygen",atoms:["O","O"],bond:"Nonpolar covalent",geometry:"Linear",angle:"180°",mass:"31.998 g/mol",note:"Two identical oxygen atoms share electrons equally."},
  N2:{formula:"N₂",name:"Nitrogen",atoms:["N","N"],bond:"Triple covalent",geometry:"Linear",angle:"180°",mass:"28.014 g/mol",note:"The nitrogen atoms are joined by a strong triple bond."},
  NaCl:{formula:"NaCl",name:"Sodium chloride",atoms:["Na","Cl"],bond:"Ionic",geometry:"Ionic lattice",angle:"—",mass:"58.44 g/mol",note:"Sodium transfers an electron to chlorine, forming Na⁺ and Cl⁻ ions. The solid is an extended lattice rather than an isolated molecule."},
};
function Molecule({atoms}){const positions=useMemo(()=>{if(atoms.length===2)return[[-.9,0,0],[.9,0,0]];if(atoms.length===3)return[[-1.15,.25,0],[0,0,0],[1.15,.25,0]];if(atoms.length===4)return[[0,.75,0],[-.8,-.25,0],[.8,-.25,0],[0,0,.9]];return[[0,0,0],[-.85,.45,0],[.85,.45,0],[-.65,-.75,0],[.65,-.75,0]]},[atoms.length]);return <group>{positions.map((p,i)=>{const d=ELEMENTS.find(e=>e.symbol===atoms[i])||ELEMENTS[0];return <group key={`${atoms[i]}-${i}`} position={p}><mesh><sphereGeometry args={[atoms[i]==="H"?.27:.42,48,48]}/><meshPhysicalMaterial color={d.color} roughness={.18} metalness={.08} clearcoat={1} emissive={d.color} emissiveIntensity={.1}/></mesh><Text position={[0,-.62,0]} fontSize={.2} color="#cbd5e1" anchorX="center">{atoms[i]}</Text></group>})}{positions.slice(0,-1).map((p,i)=>{const q=positions[i+1],dx=q[0]-p[0],dy=q[1]-p[1],dz=q[2]-p[2],len=Math.hypot(dx,dy,dz),mid=[(p[0]+q[0])/2,(p[1]+q[1])/2,(p[2]+q[2])/2];return <mesh key={`bond-${i}`} position={mid} rotation={[0,Math.atan2(dz,Math.hypot(dx,dy)),-Math.atan2(dy,dx)]}><cylinderGeometry args={[.055,.055,len,16]}/><meshStandardMaterial color="#94a3b8"/></mesh>})}</group>}
export default function CombinationLab(){const[open,setOpen]=useState(false),[preset,setPreset]=useState("H2O");const m=PRESETS[preset];return <><button className="lab-launcher" onClick={()=>setOpen(true)}><span>🧪</span><div><small>CHEMISTRY</small><b>COMBINATION LAB</b></div></button>{open&&<div className="lab-overlay"><div className="lab-panel"><div className="lab-header"><div><small>MOLECULAR EXPLORATION</small><h2>Combination Lab</h2><p>Inspect molecular geometry, bonding and physical composition in interactive 3D.</p></div><button onClick={()=>setOpen(false)}>×</button></div><div className="lab-layout"><div className="molecule-canvas"><Canvas camera={{position:[0,0,6],fov:45}}><ambientLight intensity={1.2}/><pointLight position={[3,4,5]} intensity={25}/><Molecule atoms={m.atoms}/><OrbitControls enablePan={false}/></Canvas><div className="lab-canvas-hint">DRAG TO ROTATE · SCROLL TO ZOOM</div></div><div className="lab-info"><div className="lab-label">COMPOUND</div><h3>{m.formula}</h3><strong>{m.name}</strong><div className="lab-stat"><span>ATOMS</span><b>{m.atoms.length}</b></div><div className="lab-stat"><span>BONDING</span><b>{m.bond}</b></div><div className="lab-stat"><span>GEOMETRY</span><b>{m.geometry}</b></div><div className="lab-stat"><span>BOND ANGLE</span><b>{m.angle}</b></div><div className="lab-stat"><span>MOLAR MASS</span><b>{m.mass}</b></div><p className="lab-note">{m.note}</p><div className="preset-grid">{Object.keys(PRESETS).map(k=><button className={k===preset?"selected":""} key={k} onClick={()=>setPreset(k)}>{PRESETS[k].formula}</button>)}</div></div></div></div></div>}</>}
